### ISSUE TITLE
Programmatically start/stop Slurm

### ISSUE THREAD

**Issue by bholt** [sampsyo/cluster-workers#6]
For those use cases where a single script runs many experiments, I'd love to be able to programmatically do "slurm start" before my big loop and "slurm stop" after waiting for all the jobs to finish. That way you don't have to sit around and kill your cworkers jobs after everything finishes.

@sampsyo How do you think we could best go about refactoring the code in slurm.py to allow for an easy interface for clients? I'd like to be able to do something like:

```python
    cw.slurm_start(n=2)
    client = cw.client.ClientThread(completion, cw.slurm_master_host())
    client.start()

    # Submit a bunch of work.
    for i in range(10):
        # cw.randid() is a convenient utility function for generating
        # unique job IDs in case you don't already have natural IDs.
        jobid = cw.randid()
        print(u'submitting job {} to square {}'.format(jobid, i))
        client.submit(jobid, work, i)

    # Wait for all of the jobs to finish. This helps ensure that we see
    # the results of all of our work before shutting down the
    # interpreter.
    client.wait()
    cw.slurm_stop()
```

**Comment by sampsyo** [comment]
Cool; good call. I think it makes sense to move most of the logic currently in the `slurm.py` script to a new `cw.slurm` module. The couple of Slurm utilities currently in `cw/__init__.py` could move there too. The script could then just wrap calls to `cw.slurm.start()` and `cw.slurm.stop()`.
